version: 2.1


jobs:
  deploy-dev:
    
    docker:
        - image: cimg/php:8.0.5
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
         fingerprints: 
          - "11:7d:ae:d2:b5:c9:18:5f:1b:aa:ba:e7:dd:4f:50:f4"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: composer install

      - run: sudo apt update
      - run: sudo apt-get install rsync

      - run:
          name: Update known hosts
          command: ssh-keyscan -H 192.254.235.94 >> ~/.ssh/known_hosts

      - run:
          name: ssh login  
          command: |
            rsync -va --delete app database phpunit.xml storage artisan public/ tests bootstrap  composer.json  docker-compose.yml      resources    webpack.mix.js composer.lock  Dockerfile.dev routes config package.json	server.php bartumen@192.254.235.94:api.bartumenergy.com
      - run:
          name: Directory Listing  
          command: | 
            ssh bartumen@192.254.235.94 ls
      - run:
          name: Directory Listing  
          command: ls
workflows:
  version: 2
  Barm_deploy:
    jobs:
      - deploy-dev: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: master